<a href="https://colab.research.google.com/github/carloslizarragac/FisicaComputacional1/blob/master/Actividad7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Algebra Lineal con SciPy.

Utilizaremos la biblioteca *scipy.linalg* para operar con vectores y matrices (Arreglos de NumPy: 1-D, 2-D, 3-D, etc). 


In [26]:
# 1 de marzo de 2021
# Cargamos las bibliotecas para trabajar en Algebra Lineal

import numpy as np
import scipy.linalg as la
from numpy.linalg import matrix_power as mpow


### Arreglos de Numpy 1-D.

Los arreglos en Python, tienen: dimensión, forma y tamaño. 


In [2]:
# Definimos un arreglo 1-D
a = np.array([1,2,3,4,3,2,1])
print(a)

[1 2 3 4 3 2 1]


In [3]:
# Propiedades del arreglo anterior
print('Número de dimensiones:', a.ndim)
print('Forma (shape):', a.shape)
print('Tamaño (size):', a.size)

Número de dimensiones: 1
Forma (shape): (7,)
Tamaño (size): 7


In [4]:
# Definimos un arreglo 2-D. Pensemos en una Matriz M de 2-D.
M = np.array([[1,2],[3,4],[5,6],[7,8]])
print(M)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
# Propiedades del arreglo anterior. 
print('Número de dimensiones:', M.ndim)
print('Forma (shape):', M.shape)
print('Tamaño (size):', M.size)


Número de dimensiones: 2
Forma (shape): (4, 2)
Tamaño (size): 8


In [8]:
# Podemos seleccionar una columna 1 de la matriz M (columnas:0,1) 
col = M[:,1] 
print(col)

[2 4 6 8]


In [10]:
# Propiedades del arreglo anterior. 
print('Número de dimensiones:', col.ndim)
print('Forma (shape):', col.shape)
print('Tamaño (size):', col.size)

Número de dimensiones: 1
Forma (shape): (4,)
Tamaño (size): 4


Pero, si seleccionamos una columna de una matriz 2-D, estamos seleccionando uno de los vectores en un espacio 2-D. Tenemos que usar la función *.reshape()*

In [21]:
column = col.reshape(4,1)
print(column)

[[2]
 [4]
 [6]
 [8]]


In [22]:
# Propiedades del arreglo anterior. 
print('Número de dimensiones:', column.ndim)
print('Forma (shape):', column.shape)
print('Tamaño (size):', column.size)


Número de dimensiones: 2
Forma (shape): (4, 1)
Tamaño (size): 4


Aunque la variable 'col' y 'column' tengan los mismos datos, son dos objetos distintos.
 

### Operación y Funciones de Matrices.

**Operaciones aritméticas**

Las operaciones aritméticas +, -, /, * y ** se realizan elemento a elemento. 

Ejemplos:


In [23]:
# Definimos una matriz M
M = np.array([[1,2],[3,4]])
print(M)


[[1 2]
 [3 4]]


**Multiplicación de Matrices**


In [24]:
# Producto simple (elemento a elemento)
M*M

array([[ 1,  4],
       [ 9, 16]])

In [25]:
# Producto matricial 
M@M 

array([[ 7, 10],
       [15, 22]])

**Ejercicio 1.** Defina las siguientes matrices.

\begin{gather}
 A
 =
  \begin{bmatrix}
   1 & 3 \\
   -1 & 7
   \end{bmatrix}
\end{gather}

\begin{gather}
 B
 =
  \begin{bmatrix}
   5 & 2 \\
   1 & 2
   \end{bmatrix}
\end{gather}
 y la matrix identidad 
 \begin{gather}
 I
 =
  \begin{bmatrix}
   1 & 0 \\
   0 & 1
   \end{bmatrix}
\end{gather}
Calcule el resultado de 2*I+3*A+A@B.

Para definir la matriz identidad, se puede utilizar la función *np.eye(2, dtype=int)*. Ver manual de  [np.eye()](https://numpy.org/doc/stable/reference/generated/numpy.eye.html).




**Potencias de Matrices**

No existe un símbolo para denotar las potencias de matrices. Por eso definimos la función mpow en la 1a celda de bibliotecas.

from numpy.linalg import matrix_power as mpow

In [27]:
# Teníamos una matriz M definida. 
print(M)

[[1 2]
 [3 4]]


In [28]:
# Cuadrado: M^2 = M@M
print(M@M)
print(mpow(M,2))

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [29]:
# Quinta potencia: M^5 = M@M@M@M@M
print(M@M@M@M@M)
print(mpow(M,5))

[[1069 1558]
 [2337 3406]]
[[1069 1558]
 [2337 3406]]


**Matriz Transpuesta**
$M^T$

In [30]:
# La matriz M y su transpuesta
print(M)
print(M.T)


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [31]:
# El producto de M por M.T, debe ser una matriz simétrica.
M @ M.T

array([[ 5, 11],
       [11, 25]])

**Traza de una Matriz**

Suma de los elementos de la diagonal. Usaremos la función de NumPy: *np.trace*.


In [34]:
# Traza de la matriz M.
print(M)
print(np.trace(M))

[[1 2]
 [3 4]]
5


**Determinante de una Matrix**

Se utiliza la función [scipy.linalg.det](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.det.html#scipy.linalg.det) 


Para la matriz M, 
\begin{gather}
 M
 =
  \begin{bmatrix}
   a & b \\
   c & d
   \end{bmatrix}
\end{gather}

det(M) = $ad-bc$


In [35]:
# Determinante de la matriz M
print(M)
print(la.det(M))

[[1 2]
 [3 4]]
-2.0


**Matriz Inversa**

Se calcula con la función [scipy.linalg.inv](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv)

**Nota:** Para invertir una Matriz, su Determinante no debe ser cero.

Para una matriz $M$, la inversa $M^{-1}$

\begin{gather}
 M
 =
  \begin{bmatrix}
   a & b \\
   c & d
   \end{bmatrix}
\end{gather}

\begin{gather}
 M^{-1}
 = \frac{1}{\det(M)}
  \begin{bmatrix}
   d & -b \\
   -c & a
   \end{bmatrix}
\end{gather}

In [32]:
# Matriz inversa de M
la.inv(M)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Ejercicio 2**. Los polinomios característicos y el Teorema de Cayley-Hamilton.

El polinomio característico de una matriz M esta dado en general por la ecuación 
\begin{equation}
\det(M - \lambda I) = 0
\end{equation}
Para una matriz cuadrada M (2x2), el polinomio característico se puede escribir como
\begin{equation}
P_2 (\lambda) = \det{(M)} - \mathrm{tr \,}(M) \, \lambda + \lambda^2   
\end{equation}
y para una matriz cuadrada M (3x3), el polinomio característico resulta ser

\begin{equation}
P_3 (\lambda) = \frac{1}{6} 
[ \mathrm{tr}^3 (M) + 2 \, \mathrm{tr }(M^3) - 3 \, \mathrm{tr}(M) \mathrm{tr}(M^2) ] - 
\frac{1}{2} [ \mathrm{tr}^2 (M) - \mathrm{tr}(M^2) ] \lambda + \mathrm{tr}(M) \lambda^2 - \lambda^3
\end{equation}

[El Teorema de Cayley-Hamilton](https://en.wikipedia.org/wiki/Cayley–Hamilton_theorem) nos dice que una matriz cuadrada M (2x2), satisface el polinomio característico
\begin{equation}
P_2(M) = \det(M) - \mathrm{tr}(M) M + M^2 
\end{equation}
y en general cualquier matriz cuadrada M (nxn), satisface $P_n(M)$. 

Demuestre esto para cualquier matriz M (2x2),  ($\det(M) \neq 0$).
